doz dos zod sod E
huz hus zuy suy O
man mam nam mam E
gaz gas zag sag O
gud gut dug tug E
gez ges zeg seg O
tob top bot pot E
mad mat dam tam O
goz gos zog sog E
diz dis zid sid O
tug tuk gut kut E
dov dof vod fod O
zaz zas zas sas E
beg bek geb keb O
dor dol rod lod E
zub zup bus pus O
    E
far fal rav lav O
bev bef veb feb E
per pel rep lep O
pag pak gap kap E
    O
mog mok gom kom E
gog gok gog kog O
haz has zay say E
nun num nun mun O
boz bos zob sob E
tag tak gat kat O
ner nel ren len E
lor lol ror lor O
nad nat dan tan E
giv gif vig fig O
hiv hif viy fiy E
lib lip bir pir O
lov lof vor for E
kub kup buk puk O
med met dem tem E
fob fop bov pov O
zob zop bos pos E
bug buk gub kub O
kiv kif vik fik E
hav haf vay fay O
gev gef veg feg E
han ham nay may O
bun bum nub mub E
pen pem nep mep O
tub tup but put E
zon zom nos mos O
hod hot doy toy E
ton tom not mot O
pir pil rip lip E
mud mut dum tum O
dug duk gud kud E
lub lup bur pur O
dad dat dad tad E
nan nam nan man O
fov fof vov fov E
zud zut dus tus O
nag nak gan kan E
    O
non nom non mon E
nod not don ton O
    E
mon mom nom mom O
lug luk gur kur E
hez hes zey sey O
    E
hev hef vey fey O
neg nek gen ken E
peb pep bep pep O
zez zes zes ses E
kez kes zek sek O
geg gek geg keg E
fiv fif viv fiv O
geb gep beg peg E
fed fet dev tev O
tar tal rat lat E
    O
ted tet det tet E
    O
kib kip bik pik E
hig hik giy kiy O
mav maf vam fam E
    O
bog bok gob kob E
zug zuk gus kus O
gig gik gig kig E
    O
pid pit dip tip E
    O
toz tos zot sot E
    O
gar gal rag lag E
nug nuk gun kun O
ber bel reb leb E
bir bil rib lib O
feg fek gev kev E
ded det ded ted O
tin tim nit mit E
fub fup buv puv O
leb lep ber per E
zab zap bas pas O
bub bup bub pub E
hon hom noy moy O
nen nem nen men E
her hel rey ley O
keg kek gek kek E
koz kos zok sok O
gob gop bog pog E
dod dot dod tod O
lez les zer ser E
gab gap bag pag O
bad bat dab tab E
for fol rov lov O
nub nup bun pun E
    O
lir lil rir lir E
deb dep bed ped O
bav baf vab fab E
big bik gib kib O
zid zit dis tis E
lob lop bor por O
zag zak gas kas E
ger gel reg leg O
pev pef vep fep E
tev tef vet fet O
lid lit dir tir E
hov hof voy foy O
hin him niy miy E
foz fos zov sov O
lab lap bar par E
hur hul ruy luy O
zen zem nes mes E
zar zal ras las O
dib dip bid pid E
tiv tif vit fit O
mar mal ram lam E
zeg zek ges kes O
tov tof vot fot E
hen hem ney mey O
pod pot dop top E
fir fil riv liv O
len lem ner mer E
zer zel res les O
ziz zis zis sis E
nev nef ven fen O
bon bom nob mob E
    O
noz nos zon son E
niz nis zin sin O
dir dil rid lid E
tun tum nut mut O
ban bam nab mab E
gur gul rug lug O
mir mil rim lim E
pan pam nap map O
huv huf vuy fuy E
pon pom nop mop O
fen fem nev mev E
tad tat dat tat O
lod lot dor tor E
teg tek get ket O
tid tit dit tit E
log lok gor kor O
par pal rap lap E
zev zef ves fes O
mev mef vem fem E
bur bul rub lub O
dev def ved fed E
hiz his ziy siy O
ped pet dep tep E
lud lut dur tur O
pov pof vop fop E
nib nip bin pin O
kin kim nik mik E
nob nop bon pon O
lan lam nar mar E
zed zet des tes O
pun pum nup mup E
laz las zar sar O
    E
heb hep bey pey O
zuz zus zus sus E
din dim nid mid O
mur mul rum lum E
hog hok goy koy O
bor bol rob lob E
dob dop bod pod O
pin pim nip mip E
miv mif vim fim O
bin bim nib mib E
bib bip bib pib O
div dif vid fid E
fod fot dov tov O
paz pas zap sap E
bag bak gab kab O
hid hit diy tiy E
lag lak gar kar O
kan kam nak mak E
hed het dey tey O
gen gem neg meg E
fud fut duv tuv O
kig kik gik kik E
tog tok got kot O
dab dap bad pad E
fev fef vev fev O
kev kef vek fek E
har hal ray lay O
tib tip bit pit E
kav kaf vak fak O
nud nut dun tun E
faz fas zav sav O
tez tes zet set E
    O
ler lel rer ler E
mub mup bum pum O
hun hum nuy muy E
men mem nem mem O
kiz kis zik sik E
gan gam nag mag O
feb fep bev pev E
hib hip biy piy O
bar bal rab lab E
liz lis zir sir O
pez pes zep sep E
pob pop bop pop O
fag fak gav kav E
ken kem nek mek O
ker kel rek lek E
daz das zad sad O
teb tep bet pet E
tig tik git kit O
dez des zed sed E
zov zof vos fos O
kab kap bak pak E
bed bet deb teb O
fun fum nuv muv E
mez mes zem sem O
    E
naz nas zan san O
tir til rit lit E
nir nil rin lin O
ter tel ret let E
hug huk guy kuy O
zav zaf vas fas E
    O
tuz tus zut sut E
kug kuk guk kuk O
bov bof vob fob E
tur tul rut lut O
pav paf vap fap E
buz bus zub sub O
fez fes zev sev E
dud dut dud tud O
biv bif vib fib E
leg lek ger ker O
dar dal rad lad E
had hat day tay O
nuv nuf vun fun E
tan tam nat mat O
fur ful ruv luv E
kar kal rak lak O
zog zok gos kos E
luz lus zur sur O
led let der ter E
baz bas zab sab O
kob kop bok pok E
gag gak gag kag O
kuz kus zuk suk E
    O
mag mak gam kam E
pab pap bap pap O
gug guk gug kug E
niv nif vin fin O
gor gol rog log E
nid nit din tin O
zur zul rus lus E
kud kut duk tuk O
mib mip bim pim E
dav daf vad fad O
fan fam nav mav E
deg dek ged ked O
lav laf var far E
fab fap bav pav O
nur nul run lun E
fin fim niv miv O
fon fom nov mov E
did dit did tid O
ned net den ten E
dun dum nud mud O
hoz hos zoy soy E
beb bep beb peb O
taz tas zat sat E
zig zik gis kis O
meg mek gem kem E
hor hol roy loy O
bid bit dib tib E
mun mum num mum O
    E
biz bis zib sib O
lun lum nur mur E
zan zam nas mas O
hud hut duy tuy E
puv puf vup fup O
    E
min mim nim mim O
lon lom nor mor E
nuz nus zun sun O
kod kot dok tok E
miz mis zim sim O
tor tol rot lot E
dub dup bud pud O
bob bop bob pob E
nav naf van fan O
gov gof vog fog E
fer fel rev lev O
kuv kuf vuk fuk E
gid git dig tig O
lin lim nir mir E
mab map bam pam O
mob mop bom pom E
ten tem net met O
dur dul rud lud E
fib fip biv piv O
bab bap bab pab E
maz mas zam sam O
zeb zep bes pes E
    O
por pol rop lop E
lig lik gir kir O
zir zil ris lis E
ked ket dek tek O
hab hap bay pay E
zun zum nus mus O
ben bem neb meb E
liv lif vir fir O
kaz kas zak sak E
bod bot dob tob O
tuv tuf vut fut E
nov nof von fon O
kad kat dak tak E
loz los zor sor O
poz pos zop sop E
tod tot dot tot O
hob hop boy poy E
den dem ned med O
mod mot dom tom E
peg pek gep kep O
keb kep bek pek E
tab tap bat pat O
duv duf vud fud E
giz gis zig sig O
mer mel rem lem E
tiz tis zit sit O
kor kol rok lok E
pib pip bip pip O
nez nes zen sen E
pug puk gup kup O
bud but dub tub E
kur kul ruk luk O
dan dam nad mad E
zad zat das tas O
pog pok gop kop E
lev lef ver fer O
pub pup bup pup E
fiz fis ziv siv O
lad lat dar tar E
zod zot dos tos O
fuz fus zuv suv E
mor mol rom lom O
fuv fuf vuv fuv E
zoz zos zos sos O
dag dak gad kad E
pur pul rup lup O
    E
zor zol ros los O
fav faf vav fav E
hir hil riy liy O
piv pif vip fip E
gir gil rig lig O
bez bes zeb seb E
don dom nod mod O
tud tut dut tut E
mid mit dim tim O
hub hup buy puy E
muv muf vum fum O
ziv zif vis fis E
pad pat dap tap O
nin nim nin min E
kir kil rik lik O
gub gup bug pug E
fig fik giv kiv O
zin zim nis mis E
meb mep bem pem O
lar lal rar lar E
lur lul rur lur O
buv buf vub fub E
mig mik gim kim O
gun gum nug mug E
ged get deg teg O
der del red led E
guv guf vug fug O
gad gat dag tag E
nab nap ban pan O
muz mus zum sum E
nar nal ran lan O
pud put dup tup E
kon kom nok mok O
    E
duz dus zud sud O
luv luf vur fur E
    O
fid fit div tiv E
neb nep ben pen O
nor nol ron lon E
guz gus zug sug O
    E
    O
moz mos zom som E
puz pus zup sup O
zuv zuf vus fus E